/*Question 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


var fib=[1,2];//start off the series

function sumEvenFib(max){
while(fib[fib.length-1]<max){
 var next= fib[fib.length-1]+ fib[fib.length-2];// add last 2 together and push to array
 fib.push(next);
}

//filter to have only even of the array
var evenFib= fib.filter(function(number){
return number%2===0;
});

//reduce to add together
var sum= evenFib.reduce(function(a,b){
    return a+b;   
});
console.log(sum);
}

sumEvenFib(4000000);
